version: 1.0.{build}

image: Visual Studio 2019

platform: Any CPU
configuration: Release

before_build:
  - nuget restore
  - dotnet restore

build:
  parallel: true
  project: EventLogBencher.sln

after_build:
  - 7z a EventLogBencher.zip .\EventLogBencher\bin\Release\*
  - 7z a FileLoggingBencher.zip .\FileLoggingBencher\bin\Release\*
  - dotnet publish .\BenchmarkPerformanceMonitor\ -c release -r win-x64
  - 7z a BenchmarkPerformanceMonitor-netcoreapp2.2-win-x64.zip ".\BenchmarkPerformanceMonitor\bin\ANY CPU\Release\netcoreapp2.2\win-x64\publish\*"
  - 7z a BenchmarkPerformanceMonitorUnix.zip ".\BenchmarkPerformanceMonitorUnix\*"

test: off

artifacts:
  - path: EventLogBencher.zip
    name: EventLogBencher
  - path: FileLoggingBencher.zip
    name: FileLoggingBencher
  - path: BenchmarkPerformanceMonitor-netcoreapp2.2-win-x64.zip
    name: BenchmarkPerformanceMonitor-netcoreapp2.2-win-x64
  - path: BenchmarkPerformanceMonitorUnix.zip
    name: BenchmarkPerformanceMonitorUnix

deploy:
  provider: GitHub
  auth_token:
    secure: 7XdoaFISgIXPlmVTNkMMS5cOhQzCQ06N1ksjNsres/dAyMYbT8CTxnV9KgHabwww
  artifact:  /.*\.zip/           # upload zip archives to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only